// Generated by CoffeeScript 1.3.3
(function() {
  var Exporter;

  Exporter = (function() {

    function Exporter() {}

    Exporter.prototype.save = function() {
      var header, metadata, unit, version;
      version = "1.0";
      unit = "millimeter";
      metadata = {
        description: "Production 123",
        author: "John Smith",
        copyright: "Smith & Co. 2012",
        cad: "node-potter",
        name: "foo",
        revision: "0.0.0"
      };
      return header = "<?xml version=\"" + version + "\"?>\n  <amf unit=\"" + unit + "\">\n    \n    <metadata type=\"description\">Product 123</metadata>\n\n    ...\n    <object ObjectID=\"0\">\n      <metadata type=\"name\">Component 1</metadata>\n      ...\n    </object>\n</amf>";
    };

    return Exporter;

  })();

}).call(this);
