// Generated by CoffeeScript 1.4.0
(function() {
  var Exporter;

  Exporter = (function() {

    function Exporter() {}

    Exporter.prototype.save = function() {
      var buff, p, _i, _len, _results;
      buff = "";
      _results = [];
      for (_i = 0, _len = points.length; _i < _len; _i++) {
        p = points[_i];
        _results.push(buff += "" + x + " " + y + " " + z + "\n");
      }
      return _results;
    };

    return Exporter;

  })();

}).call(this);
