// Generated by CoffeeScript 1.3.3
(function() {
  var Exporter;

  Exporter = (function() {

    function Exporter() {}

    Exporter.prototype.save = function() {
      var buff, header, headerOrder, key, point, points, value, _i, _j, _len, _len1, _results;
      points = [];
      header = {
        version: '.7',
        fields: "x y z rgb",
        size: "4 4 4 4",
        type: "I I I I",
        count: "1 1 1 1",
        width: 213,
        height: 1,
        viewpoint: "0 0 0 1 0 0 0",
        points: points.length,
        data: 'ascii'
      };
      headerOrder = ['version', 'fields', 'size', 'type', 'count', 'width', 'height', 'viewpoint', 'points', 'data'];
      buff = "";
      for (_i = 0, _len = headerOrder.length; _i < _len; _i++) {
        key = headerOrder[_i];
        value = header[key];
        buff += "" + (key.toUpperCase()) + " " + value;
      }
      _results = [];
      for (_j = 0, _len1 = points.length; _j < _len1; _j++) {
        point = points[_j];
        _results.push(buff += "" + p.x + " " + p.y + " " + p.z + " " + p.material.rgb);
      }
      return _results;
    };

    return Exporter;

  })();

}).call(this);
