// Generated by CoffeeScript 1.4.0
(function() {
  var Exporter;

  Exporter = (function() {

    function Exporter() {}

    Exporter.prototype.save = function() {};

    return Exporter;

  })();

}).call(this);
