// Generated by CoffeeScript 1.3.3
(function() {
  var Exporter;

  Exporter = (function() {

    function Exporter() {}

    Exporter.prototype.save = function() {
      var buff, name;
      name = "foo";
      buff = "";
      buff += "solid " + name + "\n";
      "facet normal ni nj nk\nouter loop\nvertex v1x v1y v1z\nvertex v2x v2y v2z\nvertex v3x v3y v3z\nendloop\nendfacet";

      return buff += "endsolid " + name + "\n";
    };

    return Exporter;

  })();

}).call(this);
