// Generated by CoffeeScript 1.3.3
(function() {
  var Potter, async, clay, error, inspect, log, metal, p1, p2, p3, p4, path, plastic, pot, rad, sphere, wait, _ref, _ref1;

  _ref = require('util'), log = _ref.log, error = _ref.error, inspect = _ref.inspect;

  _ref1 = require('./toolbox'), wait = _ref1.wait, async = _ref1.async;

  Potter = require('./potter');

  sphere = function(x, y, r) {};

  pot = new Potter({
    size: [100, 100, 100]
  });

  clay = pot.createMaterial("clay", "brown");

  plastic = pot.createMaterial("plastic", "red");

  metal = pot.createMaterial("metal", "grey");

  pot.use(plastic);

  pot.dot([5, 5, 5]);

  pot.dot([4, 5, 6]);

  pot.dot([5, 3, 7]);

  pot.use(clay);

  p1 = [20, 20, 15];

  p2 = [15, 40, 15];

  p3 = [30, 20, 30];

  p4 = [40, 30, 40];

  path = [p1, p2, p3, p4];

  log("starting walk..");

  rad = 15;

  pot.walk(path, function(p) {
    log("@" + p);
    rad -= Math.random() * 0.3;
    if (rad < 2) {
      rad = 1;
    }
    return pot.sphere(p, rad);
  });

  pot.save("examples/exports/test.stl", function() {
    return log("file saved");
  });

}).call(this);
