// Generated by CoffeeScript 1.3.3
(function() {
  var Potter, body, dog, error, fur, inspect, leg, log, name, pbl, pbr, pbt, pfl, pfr, pft, _ref;

  _ref = require('util'), log = _ref.log, error = _ref.error, inspect = _ref.inspect;

  Potter = require('potter');

  name = "dog";

  dog = new Potter({
    size: [100, 100, 100]
  });

  fur = dog.createMaterial("plastic", "brown");

  dog.use(fur);

  pfr = [10, 10, 10];

  pft = [20, 20, 20];

  pfl = [10, 30, 10];

  pbr = [50, 10, 10];

  pbt = [40, 20, 20];

  pbl = [50, 30, 10];

  log("drawing..");

  leg = function(p) {
    return dog.sphere(p, 4);
  };

  body = function(p) {
    return dog.sphere(p, 8);
  };

  dog.trace([pfr, pft, pfl], leg);

  dog.trace([pft, pbt], body);

  dog.trace([pbr, pbt, pbl], leg);

  log("saving..");

  dog.save("examples/exports/" + name + ".stl", function() {
    return log("file saved");
  });

}).call(this);
